#include "includes.h"

#ifndef _FT_JSON_H_
#define _FT_JSON_H_

enum tweet_element {
    TWTELM_PLACE,
    TWTELM_GEO,
    TWTELM_RETWEETED,
    TWTELM_TEXT,
    TWTELM_IN_REPLY_TO_STATUS_ID_STR,
    TWTELM_IN_REPLY_TO_STATUS_ID,
    TWTELM_IN_REPLY_TO_USER_ID_STR,
    TWTELM_TRUNCATED,
    TWTELM_POSSIBLY_SENSITIVE_EDITABLE,
    TWTELM_SOURCE,
    TWTELM_IN_REPLY_TO_USER_ID,
    TWTELM_CONTRIBUTORS,
    TWTELM_RETWEET_COUNT,
    TWTELM_FAVORITED,
    TWTELM_CREATED_AT,
    TWTELM_COORDINATES,
    TWTELM_POSSIBLY_SENSITIVE,
    TWTELM_ID_STR,
    TWTELM_USER,
    TWTELM_IN_REPLY_TO_SCREEN_NAME,
    TWTELM_ID,
    TWTELM_ENTITIES,
    TWTELM_UNDEF
};

enum tweet_element tokenize (char *key);
int tweet_create_from_json(char *tweet);

#endif
